### ISSUE TITLE
Writing to Azure appears to stop after 10/15 minutes of app running

### ISSUE THREAD

**Issue by buzallen** [serilog/serilog-sinks-azuredocumentdb#41]
This is .net core with MVC 1.0.1  running as an App Service in Azure.  Does not exhibit this issue when running locally with the DocumentDB emulator from VS.  When I start up the app the logging works as expected and then about 1/15 minutes after the app was started the logs stop being written to the database.  I'm not seeing any exceptions.  This is what I am using to configure:

`Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Override("Microsoft", LogEventLevel.Warning)
                .MinimumLevel.Override("Hangfire", LogEventLevel.Warning)
                .MinimumLevel.Override("System", LogEventLevel.Error)
                .Enrich.FromLogContext()
                .WriteTo.AzureDocumentDB(connectionInfo.EndPoint,
                                        connectionInfo.Key,
                                        databaseName: connectionInfo.DbName,
                                        collectionName: connectionInfo.Collection)
                                        .CreateLogger();`

I am also using the provided code to init the service:

`            loggerFactory.AddSerilog();
            appLifetime.ApplicationStopped.Register(Log.CloseAndFlush);`

If I restart the app then it works again for 10/15 and then stops.

Going to clone the repo and try to run it locally and see if I can see what I'm doing wrong or if there is a bug.

**Comment by nblumhardt** [comment]
Thanks for the report - sounds like some investigation is needed. Let us know if you need help making sense of what's going on in there 👍

**Comment by saleem-mirza** [comment]
@buzallen, Thanks for reporting issue. I'll investigate what's going on. However, this sink is using `preview` version of Microsoft Azure DocumentDB driver so bugs are expected and may not be used for production. Please see https://www.nuget.org/packages/Microsoft.Azure.DocumentDB.Core/

**Comment by buzallen** [comment]
Thanks @saleem-mirza , that's a good point.  I'm testing sinks for now but I'll keep that in mind when it's time to move forward.

**Comment by saleem-mirza** [comment]
@buzallen @nblumhardt 

I have created a test dotnet core web application with Serilog.Sinks.AzureDocumentDB sink configured  and deployed as Azure App Service. It's been running for few hours and I haven't noticed any issue with logging.

Please keep in mind that new sink requires dotnet core version 1.1.0+. I'm closing this issue. However, if you still have issue with sink, feel free to leave a message.

**Comment by nblumhardt** [comment]
Saleem, you're a powerhouse :-) kudos for all of your work on this sink!

**Comment by buzallen** [comment]
Thanks @saleem-mirza.  Interesting I still have the issue even with a new clean project.  I'll have to investigate if something is configured incorrectly on my end.  I get about 5 minutes of logs to the document db and then it stops writing anything.  I'll re-post here if I discover anything.  Thanks again.

**Comment by saleem-mirza** [comment]
@buzallen my `project.json`, `Startup.cs` and `Controller` looks like as

>Note: I removed unrelated stuff for sake of brevity

**project.json**
```json
    {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "version": "1.1.0",
          "type": "platform"
        },
        "Serilog": "2.3.0",
        "Serilog.Sinks.AzureDocumentDb": "3.5.17"
      },
      "frameworks": {
        "netcoreapp1.6": {
          "imports": [
            "dotnet5.6",
            "dnxcore50",
            "portable-net45+win8"
          ]
        }
      }
    }
 ```

**Startup.cs** (ConfigureServices)

```C#
        public void ConfigureServices(IServiceCollection services)
        {
            // Add framework services.
            services.AddDbContext<ApplicationDbContext>(options =>
                options.UseSqlite(Configuration.GetConnectionString("DefaultConnection")));

            services.AddIdentity<ApplicationUser, IdentityRole>()
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddDefaultTokenProviders();

            services.AddMvc();

            services.AddSingleton<Serilog.ILogger>(
                new Serilog.LoggerConfiguration()
                .WriteTo.AzureDocumentDB(
                    "https://xxxxx.documents.azure.com:443/",
                    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
                )
                .MinimumLevel.Verbose()
                .CreateLogger());
        }

```

**HomeController.cs**

```C#
    public class HomeController : Controller
    {
        Serilog.ILogger _logger;

        public HomeController(Serilog.ILogger logger)
        {
            _logger = logger;
            _logger.Information("HomeController constructor called.");
        }

    ...
```

Hopefully, it will shed some light.

**Comment by buzallen** [comment]
Thanks again @saleem-mirza .  Switching to your implementation does work.  For reasons I'm unsure of when I set it up like I do in my original post above is when it stops logging.
