### ISSUE TITLE
CreateDatabaseIfNotExistsAsync not working when using newer ddb client

### ISSUE THREAD

**Issue by vip32** [serilog/serilog-sinks-azuredocumentdb#42]
Hi,
when using this sink with the newer Microsoft.Azure.DocumentDB Client (1.11.1) the following error occurs at runtime: 

```[MissingMethodException: Method not found: 'System.Threading.Tasks.Task Microsoft.Azure.Documents.Client.DocumentClient.OpenAsync()'.]
   Serilog.Sinks.AzureDocumentDb.<CreateDatabaseIfNotExistsAsync>d__12.MoveNext() +0
   System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start(TStateMachine& stateMachine) +124
   Serilog.Sinks.AzureDocumentDb.AzureDocumentDBSink.CreateDatabaseIfNotExistsAsync(String databaseName) +137
```
it seems that the OpenAsync() on the client lib has changed slightly: an optional cancellation token can now be supplied. 

old: 
![image](https://cloud.githubusercontent.com/assets/164303/21680498/6fba94e0-d34a-11e6-9a2f-3c490e9dc5b1.png)

new: 
![image](https://cloud.githubusercontent.com/assets/164303/21680516/85a2405a-d34a-11e6-90ee-846d967d3314.png)

i cannot explain this runtime behaviour as it is a new optional argument, it should work ;)

i would love to do a PR and update this project so it uses ddb client 1.11.1 and this issue probably will go away. however i have a hard time even opening this core project in vs15/17rc (nothing but vs errors). will later try on another box...

**Comment by vip32** [comment]
i finally managed on another box, please have a look at PR #43

**Comment by saleem-mirza** [comment]
@vip32 your changes have been published on nuget. Please see https://www.nuget.org/packages/Serilog.Sinks.AzureDocumentDb/3.5.18-dev-00119
