### ISSUE TITLE
Dictionary<,> Not Serializing properly

### ISSUE THREAD

**Issue by maldworth** [serilog/serilog-sinks-azuredocumentdb#46]
I was looking at the documentation [here](https://github.com/serilog/serilog/wiki/Structured-Data) and in the __collections__ section, it has this example:

```csharp
var fruit = new Dictionary<string,int> {{ "Apple", 1}, { "Pear", 5 }};
Log.Information("In my bowl I have {Fruit}", fruit);
```

So I tried that, and I get in Document DB:

```json
{
  "EventIdHash": 2098721849,
  "Timestamp": "2017-03-15 19:46:13.712-04:00",
  "Level": "Information",
  "Message": "In my bowl I have [(\"Apple\": 1), (\"Pear\": 5)]",
  "MessageTemplate": "In my bowl I have {Fruit}",
  "Exception": null,
  "Properties": {
    "Fruit": null,
    "SourceContext": "MyProgram.MyClass"
  },
  "id": "b62d1578-2056-6335-21a4-57655c12f22e"
}
```

1. The Message is wrong, it should be `{ "Fruit": ["Apple", "Pear", "Orange"] }`
2. The property is also null `"Fruit": null`

Now if you just run a simple console app:

```csharp
namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            var logger = new LoggerConfiguration()
				.WriteTo.Console().CreateLogger();
                //.WriteTo.Console(formatter: new JsonFormatter()).CreateLogger();

            var fruit = new Dictionary<string, int> { { "Apple", 1 }, { "Pear", 5 } };
            logger.Information("In my bowl I have {@Fruit}", fruit);


            Console.ReadKey();
        }
    }
}
```

the output is the same:

```
2017-03-15 20:40:20 [Information] In my bowl I have [("Apple": 1), ("Pear": 5)]

```

But if you comment out the first line, and add in the [JsonFormatter](https://github.com/serilog/serilog/wiki/Formatting-Output), then the Dictionary works and everything looks great... but in the console.

```
{"Timestamp":"2017-03-15T20:41:21.0136426-04:00","Level":"Information","MessageTemplate":"In my bowl I have {@Fruit}","Properties":{"Fruit":{"Apple":1,"Pear":5}}}
```

The DocumentDb sink doesn't have the capability to pass `new JsonFormatter()`.

Let me know if you need more information

**Comment by nblumhardt** [comment]
Looks like the problem is here:

https://github.com/serilog/serilog-sinks-azuredocumentdb/blob/dev/src/Serilog.Sinks.AzureDocumentDb/Sinks/Extensions/LogEventExtensions.cs#L92

Instead of `as IReadOnlyDictionary<...>`, this should be `as DictionaryValue`.

**Comment by saleem-mirza** [comment]
@nblumhardt good catch. Thank you!

**Comment by saleem-mirza** [comment]
@maldworth, appreciated for contribution!
