### ISSUE TITLE
Logging works only for the first time and stops there after

### ISSUE THREAD

**Issue by sajanep** [serilog/serilog-sinks-azuredocumentdb#48]
I am using .NET Framework 4.6.1. Developed a logger component on top of Serilog and wanted to use Azure Document Db sink. I am getting a strange behavior. My first log statement appears in Document Db, but the subsequent log messages are not coming. After deleting the first document, again logging happens only first time and never happens again. Below is my code
```
internal class SeriLogger : ILogger
    {
        private static readonly string EndpointUri = "https://mysample.documents.azure.com:443/";
        private static readonly string AuthKey = "UkgOMJT08bA5KOvd1O9IYgo0w==";
        private static readonly string DatabaseName = "Diagnostics";
        private static readonly string CollectionName = "Logs";

        protected readonly Serilog.Core.Logger logger;

        public SeriLogger()
        {
            logger = new LoggerConfiguration()
            .WriteTo.AzureDocumentDB(EndpointUri, AuthKey, DatabaseName, CollectionName)
                .CreateLogger();
            //logger = new LoggerConfiguration()
            //.WriteTo.RollingFile(Path.Combine(
            //    AppDomain.CurrentDomain.BaseDirectory, "log-{Date}.txt"), fileSizeLimitBytes: 536870912)
            //    .CreateLogger();
        }

public void Log(string message, LogLevelEnum logLevel)
        {
            switch (logLevel)
            {
                case LogLevelEnum.Debug: logger.Debug(message); break;
                case LogLevelEnum.Information: logger.Information(message); break;
                case LogLevelEnum.Warning: logger.Warning(message); break;
                case LogLevelEnum.Error: logger.Error(message); break;
                case LogLevelEnum.Fatal: logger.Fatal(message); break;
            }
        }

```
Below are the Nuget versions I am using
`<packages>
  <package id="Microsoft.Azure.DocumentDB" version="1.11.1" targetFramework="net461" />
  <package id="Newtonsoft.Json" version="6.0.8" targetFramework="net461" />
  <package id="Serilog" version="2.4.0" targetFramework="net461" />
  <package id="Serilog.Sinks.AzureDocumentDb" version="3.5.18" targetFramework="net461" />
  <package id="Serilog.Sinks.File" version="3.2.0" targetFramework="net461" />
  <package id="Serilog.Sinks.RollingFile" version="3.3.0" targetFramework="net461" />
</packages>
`
But the logging works perfectly with Rolling File sink. Please help me.

I tried to enable diagnostics for serilog like below 
`Serilog.Debugging.SelfLog.Enable(msg => Debug.WriteLine(msg)); `
Now I can see two lines in my VS output window. 
2017-03-14T07:40:18.5291346Z Sending batch of 2 messages to DocumentDB 2017-03-14T07:40:22.1107764Z One or more errors occurred.

**Comment by saleem-mirza** [comment]
Sandeep, we'll investigate issue.

**Comment by saleem-mirza** [comment]
I figured out current implementation wasn't fully optimized for .net 4.6.1. However I recently updated new version so please try it and let me know if it works.

**Comment by sajanep** [comment]
Hello Saleem,
I tried just now. But I am getting the below exception in VS Output window

> 2017-03-18T18:34:48.5194083Z Sending batch of 1 messages to DocumentDB
> The thread 0x2fd0 has exited with code 0 (0x0).
> The thread 0x138c has exited with code 0 (0x0).
> The thread 0x1cf8 has exited with code 0 (0x0).
> The thread 0x2934 has exited with code 0 (0x0).
> The thread 0x151c has exited with code 0 (0x0).
> The thread 0x27f4 has exited with code 0 (0x0).
> DocDBTrace Error: 0 : DocumentClientException with status code: BadRequest, message: Message: {"Errors":["Encountered exception while executing Javascript. Exception = Error: The array is undefined or null.\r\nStack trace: Error: The array is undefined or null.\n   at bulkImport (BulkImport.js:8:16)\n   at __docDbMain (BulkImport.js:30:5)\n   at Global code (BulkImport.js:1:2)"]}
> ActivityId: b83b569a-fd8f-4294-85d0-c55f59e11e8d, Request URI: /apps/ada95054-28af-44b4-811c-3fd5a457ab2a/services/474e9d63-5cf1-4c4c-880d-e2a70ba57dc6/partitions/8fc6bc7b-d033-4ad6-bd9c-fd46d6edbe3c/replicas/131339384456389699p, and response headers: {
> "Transfer-Encoding": "chunked",
> "x-ms-last-state-change-utc": "Tue, 14 Mar 2017 18:12:32.584 GMT",
> "x-ms-schemaversion": "1.3",
> "x-ms-quorum-acked-lsn": "17723",
> "x-ms-current-write-quorum": "3",
> "x-ms-current-replica-set-size": "4",
> "x-ms-xp-role": "1",
> "x-ms-request-charge": "5.7",
> "x-ms-serviceversion": "version=1.11.169.3",
> "x-ms-activity-id": "b83b569a-fd8f-4294-85d0-c55f59e11e8d",
> "x-ms-session-token": "0:17723",
> "Strict-Transport-Security": "max-age=31536000",
> "x-ms-gatewayversion": "version=1.11.169.3",
> "Date": "Sat, 18 Mar 2017 18:34:56 GMT",
> "Server": "Microsoft-HTTPAPI/2.0",
> }
> DocDBTrace Error: 0 : Operation will NOT be retried. Current attempt 0, Exception: Microsoft.Azure.Documents.DocumentClientException: Message: {"Errors":["Encountered exception while executing Javascript. Exception = Error: The array is undefined or null.\r\nStack trace: Error: The array is undefined or null.\n   at bulkImport (BulkImport.js:8:16)\n   at __docDbMain (BulkImport.js:30:5)\n   at Global code (BulkImport.js:1:2)"]}
> ActivityId: b83b569a-fd8f-4294-85d0-c55f59e11e8d, Request URI: /apps/ada95054-28af-44b4-811c-3fd5a457ab2a/services/474e9d63-5cf1-4c4c-880d-e2a70ba57dc6/partitions/8fc6bc7b-d033-4ad6-bd9c-fd46d6edbe3c/replicas/131339384456389699p
>    at Microsoft.Azure.Documents.Client.ClientExtensions.<ParseResponseAsync>d__4.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
>    at Microsoft.Azure.Documents.GatewayStoreModel.<>c__DisplayClass10.<<InvokeAsync>b__f>d__12.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Azure.Documents.BackoffRetryUtility`1.<>c__DisplayClass2.<<ExecuteAsync>b__0>d__4.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Azure.Documents.BackoffRetryUtility`1.<ExecuteRetry>d__1b.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.Azure.Documents.BackoffRetryUtility`1.<ExecuteRetry>d__1b.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Azure.Documents.BackoffRetryUtility`1.<ExecuteAsync>d__a.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Azure.Documents.GatewayStoreModel.<InvokeAsync>d__1f.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Azure.Documents.GatewayStoreModel.<ProcessMessageAsync>d__2.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Azure.Documents.Client.DocumentClient.<ExecuteProcedureAsync>d__314.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Azure.Documents.Client.DocumentClient.<ExecuteStoredProcedurePrivateAsync>d__241`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Azure.Documents.BackoffRetryUtility`1.<>c__DisplayClass2.<<ExecuteAsync>b__0>d__4.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Azure.Documents.BackoffRetryUtility`1.<ExecuteRetry>d__1b.MoveNext() 
> DocDBTrace Error: 0 : DocumentClientException with status code: BadRequest, message: Message: {"Errors":["Encountered exception while executing Javascript. Exception = Error: The array is undefined or null.\r\nStack trace: Error: The array is undefined or null.\n   at bulkImport (BulkImport.js:8:16)\n   at __docDbMain (BulkImport.js:30:5)\n   at Global code (BulkImport.js:1:2)"]}
> ActivityId: 94049472-dd9f-478a-8ae5-8b7055f6162e, Request URI: /apps/ada95054-28af-44b4-811c-3fd5a457ab2a/services/474e9d63-5cf1-4c4c-880d-e2a70ba57dc6/partitions/8fc6bc7b-d033-4ad6-bd9c-fd46d6edbe3c/replicas/131339384456389699p, and response headers: {
> "Transfer-Encoding": "chunked",
> "x-ms-last-state-change-utc": "Tue, 14 Mar 2017 18:12:32.584 GMT",
> "x-ms-schemaversion": "1.3",
> "x-ms-quorum-acked-lsn": "17723",
> "x-ms-current-write-quorum": "3",
> "x-ms-current-replica-set-size": "4",
> "x-ms-xp-role": "1",
> "x-ms-request-charge": "4.89",
> "x-ms-serviceversion": "version=1.11.169.3",
> "x-ms-activity-id": "94049472-dd9f-478a-8ae5-8b7055f6162e",
> "x-ms-session-token": "0:17723",
> "Strict-Transport-Security": "max-age=31536000",
> "x-ms-gatewayversion": "version=1.11.169.3",
> "Date": "Sat, 18 Mar 2017 18:34:56 GMT",
> "Server": "Microsoft-HTTPAPI/2.0",
> }
> DocDBTrace Error: 0 : Operation will NOT be retried. Current attempt 0, Exception: Microsoft.Azure.Documents.DocumentClientException: Message: {"Errors":["Encountered exception while executing Javascript. Exception = Error: The array is undefined or null.\r\nStack trace: Error: The array is undefined or null.\n   at bulkImport (BulkImport.js:8:16)\n   at __docDbMain (BulkImport.js:30:5)\n   at Global code (BulkImport.js:1:2)"]}
> ActivityId: 94049472-dd9f-478a-8ae5-8b7055f6162e, Request URI: /apps/ada95054-28af-44b4-811c-3fd5a457ab2a/services/474e9d63-5cf1-4c4c-880d-e2a70ba57dc6/partitions/8fc6bc7b-d033-4ad6-bd9c-fd46d6edbe3c/replicas/131339384456389699p
>    at Microsoft.Azure.Documents.Client.ClientExtensions.<ParseResponseAsync>d__4.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
>    at Microsoft.Azure.Documents.GatewayStoreModel.<>c__DisplayClass10.<<InvokeAsync>b__f>d__12.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Azure.Documents.BackoffRetryUtility`1.<>c__DisplayClass2.<<ExecuteAsync>b__0>d__4.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Azure.Documents.BackoffRetryUtility`1.<ExecuteRetry>d__1b.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.Azure.Documents.BackoffRetryUtility`1.<ExecuteRetry>d__1b.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Azure.Documents.BackoffRetryUtility`1.<ExecuteAsync>d__a.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Azure.Documents.GatewayStoreModel.<InvokeAsync>d__1f.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Azure.Documents.GatewayStoreModel.<ProcessMessageAsync>d__2.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Azure.Documents.Client.DocumentClient.<ExecuteProcedureAsync>d__314.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Azure.Documents.Client.DocumentClient.<ExecuteStoredProcedurePrivateAsync>d__241`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Azure.Documents.BackoffRetryUtility`1.<>c__DisplayClass2.<<ExecuteAsync>b__0>d__4.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Azure.Documents.BackoffRetryUtility`1.<ExecuteRetry>d__1b.MoveNext()

**Comment by saleem-mirza** [comment]
ah. it's not good. Please get latest and try again. thank you

**Comment by sajanep** [comment]
Hello Saleem,
Still its same. Logs are not getting generated and I am getting the below exceptions, while writing

```
2017-03-19T05:10:05.6324023Z Sending batch of 2 messages to DocumentDB
DocDBTrace Error: 0 : DocumentClientException with status code: BadRequest, message: Message: {"Errors":["Encountered exception while executing Javascript. Exception = Error: The array is undefined or null.\r\nStack trace: Error: The array is undefined or null.\n   at bulkImport (BulkImport.js:8:16)\n   at __docDbMain (BulkImport.js:30:5)\n   at Global code (BulkImport.js:1:2)"]}
ActivityId: 7b6db1bf-f711-4e5b-a2d6-97946419fe6d, Request URI: /apps/ada95054-28af-44b4-811c-3fd5a457ab2a/services/474e9d63-5cf1-4c4c-880d-e2a70ba57dc6/partitions/8fc6bc7b-d033-4ad6-bd9c-fd46d6edbe3c/replicas/131339384456389699p, and response headers: {
"Transfer-Encoding": "chunked",
"x-ms-last-state-change-utc": "Tue, 14 Mar 2017 18:12:32.584 GMT",
"x-ms-schemaversion": "1.3",
"x-ms-quorum-acked-lsn": "17725",
"x-ms-current-write-quorum": "3",
"x-ms-current-replica-set-size": "4",
"x-ms-xp-role": "1",
"x-ms-request-charge": "4.08",
"x-ms-serviceversion": "version=1.11.169.3",
"x-ms-activity-id": "7b6db1bf-f711-4e5b-a2d6-97946419fe6d",
"x-ms-session-token": "0:17725",
"Strict-Transport-Security": "max-age=31536000",
"x-ms-gatewayversion": "version=1.11.169.3",
"Date": "Sun, 19 Mar 2017 05:10:09 GMT",
"Server": "Microsoft-HTTPAPI/2.0",
}
DocDBTrace Error: 0 : Operation will NOT be retried. Current attempt 0, Exception: Microsoft.Azure.Documents.DocumentClientException: Message: {"Errors":["Encountered exception while executing Javascript. Exception = Error: The array is undefined or null.\r\nStack trace: Error: The array is undefined or null.\n   at bulkImport (BulkImport.js:8:16)\n   at __docDbMain (BulkImport.js:30:5)\n   at Global code (BulkImport.js:1:2)"]}
ActivityId: 7b6db1bf-f711-4e5b-a2d6-97946419fe6d, Request URI: /apps/ada95054-28af-44b4-811c-3fd5a457ab2a/services/474e9d63-5cf1-4c4c-880d-e2a70ba57dc6/partitions/8fc6bc7b-d033-4ad6-bd9c-fd46d6edbe3c/replicas/131339384456389699p
   at Microsoft.Azure.Documents.Client.ClientExtensions.<ParseResponseAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Azure.Documents.GatewayStoreModel.<>c__DisplayClass10.<<InvokeAsync>b__f>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Documents.BackoffRetryUtility`1.<>c__DisplayClass2.<<ExecuteAsync>b__0>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Documents.BackoffRetryUtility`1.<ExecuteRetry>d__1b.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Documents.BackoffRetryUtility`1.<ExecuteRetry>d__1b.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Documents.BackoffRetryUtility`1.<ExecuteAsync>d__a.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Documents.GatewayStoreModel.<InvokeAsync>d__1f.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Documents.GatewayStoreModel.<ProcessMessageAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Documents.Client.DocumentClient.<ExecuteProcedureAsync>d__314.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Documents.Client.DocumentClient.<ExecuteStoredProcedurePrivateAsync>d__241`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Documents.BackoffRetryUtility`1.<>c__DisplayClass2.<<ExecuteAsync>b__0>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Documents.BackoffRetryUtility`1.<ExecuteRetry>d__1b.MoveNext() 
2017-03-19T05:10:05.7944023Z Getting required resource.
```
I am wondering why .NET 4.6.1 is not supported yet even though .NET Core is supported. According to me .NET Core is still a baby, and the industry is yet to adopt it.

**Comment by saleem-mirza** [comment]
This error is coming from DocumentsDB itself. I'll send you demo code I used to test.

**Comment by saleem-mirza** [comment]
@sajanep, I'm not able to duplicate issue you mentioned above; may be I'm missing something. Make sure you got latest bits from nuget. Current version is [3.6.1](https://www.nuget.org/packages/Serilog.Sinks.AzureDocumentDb/3.6.1)

I'm attaching demo C# and packages.config file:

> Program.cs

```C#
using Serilog;
using Serilog.Debugging;
using System;

namespace serilogDemo
{
    class Program
    {
        static void Main(string[] args)
        {
            var endPointUrl = "https://xxxxxxxxxxxxxxxx.documents.azure.com:443/";
            var authKey = "xxxxxxxxxxxxxxxx";

            SelfLog.Enable(Console.Out);

            var logger = new LoggerConfiguration()
                .MinimumLevel.Debug()
                .WriteTo.AzureDocumentDB(endPointUrl, authKey)
                .CreateLogger();

            if (logger != null)
            {
                using (logger)
                {
                    for (int i = 0; i < 3000; i++)
                    {
                        logger.Debug("This is message #: {i} at {d}", i, DateTime.Now);
                    }
                }
            }
        }
    }
}

```


>packages.config

```XML
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Microsoft.Azure.DocumentDB" version="1.12.2" targetFramework="net461" />
  <package id="Newtonsoft.Json" version="6.0.8" targetFramework="net461" />
  <package id="Serilog" version="2.4.0" targetFramework="net461" />
  <package id="Serilog.Sinks.AzureDocumentDB" version="3.6.1" targetFramework="net461" />
</packages>
```

**Comment by sajanep** [comment]
Hello Saleem,
I am not sure what are we missing here. I am using the same packages as you quoted above. I can easily reproduce the issue.  I am able to reproduce the issue in a C# console application and also in ASP.NET Web Api application. Sometimes first log statement works and second one produces the big exception as mentioned earlier.

**Comment by saleem-mirza** [comment]
@sajanep are you still having issue?
