### ISSUE TITLE
NullReferenceException in LogEventExtensions.ConvertToDictionary

### ISSUE THREAD

**Issue by maldworth** [serilog/serilog-sinks-azuredocumentdb#54]
So this happens infrequently, and it's not bothering me that much but I thought I'd post it here. Here's the log history, you can see at the top it logged to DocumentDb (and that log shows up correctly), then it missed the batch of 50 for some reason. Then it continues logging happily.

This file shows the exception and stacktrace:
[logoutput.txt](https://github.com/serilog/serilog-sinks-azuredocumentdb/files/987851/logoutput.txt)

This file shows an example of what should be logged (50 times in this case) to documentDb.
[DocumentDbEntrySample.txt](https://github.com/serilog/serilog-sinks-azuredocumentdb/files/987852/DocumentDbEntrySample.txt)

Any idea what is null? Unfortunately it's not reliably reproducable. I'd be happy to submit a PR if you can point me in the right direction.

**Comment by maldworth** [comment]
Interesting Update. It seems to have stopped logging a few lines after this error occurred. So I had to restart the service for it to start logging again.

**Comment by saleem-mirza** [comment]
@maldworth, thank you for reporting. I'm traveling but will dig deep and let you know as soon as possible.

**Comment by saleem-mirza** [comment]
@maldworth. Unfortunately, I couldn't reproduce this issue. Please attach a sample code to reproduce behavior.

**Comment by saleem-mirza** [comment]
@maldworth please try beta version and let me know if it fixes issue. http://www.nuget.org/packages/Serilog.Sinks.AzureDocumentDb/3.6.8-dev-00142

**Comment by maldworth** [comment]
Hi Salem,

Thank you for the quick fix. Ran it again with 3.6.1, and issue was still there (yay). Updated to the pre-release 3.6.8-dev-00142, re-ran, and received the following exceptions:

[logoutput-prerelease.txt](https://github.com/serilog/serilog-sinks-azuredocumentdb/files/1025543/logoutput-prerelease.txt)

**Comment by saleem-mirza** [comment]
@maldworth please post sample code to reproduce this defect.

**Comment by saleem-mirza** [comment]
@maldworth please post sample code to reproduce this defect.

**Comment by maldworth** [comment]
so I've narrowed it down to happening within Azure Service Fabric. Why or when I can't reliably reproduce it. But the same code ran outside of Service Fabric is fine. So I've had to go to an alternative :(

You can close this if you like.

**Comment by saleem-mirza** [comment]
@maldworth, thanks for nailing it down. I'll try to decipher error message and let you know.

**Comment by saleem-mirza** [comment]
@maldworth, please try with latest pre-release. https://www.nuget.org/packages/Serilog.Sinks.AzureDocumentDb/3.6.8-dev-00144

**Comment by maldworth** [comment]
ok I'll give it a go this weekend and post my results. Thanks!

**Comment by maldworth** [comment]
Had some spare time to give it a try. I think it's fixed! I'll keep monitoring, and post here if it manifests again.
