### ISSUE TITLE
Error log event not saving data in DocumentDB

### ISSUE THREAD

**Issue by kumprek** [serilog/serilog-sinks-azuredocumentdb#56]
Using this serilog sink to write into Azure DocumentDB, there seams to be some issue with the sinking for Error event type i.e. in case of passing Exception object.

Here is the code snippet:

```
 public IActionResult Index()
        {
            try
            {
                int.Parse("s");
            }
            catch (Exception exception)
            {
                _logger.Error("Test error");
                _logger.Error(exception, "Test error");
                throw;
            }
            _logger.Information("test");
            return View();
        } 
```

In the above code: 
**_logger.Error("Test error");** This works well as we are not passing the exception object.
Whereas **_logger.Error(exception, "Test error");** dont log any entry in document DB as we are passing the exception object.

Is there any work-around for this, so that the exception details can be logged into DocumentDB.

**Comment by saleem-mirza** [comment]
@kumprek, thanks for reporting issue with reproducible code. I see that sink had issue with circular references, in this case exception object when used with .net core. Please try http://www.nuget.org/packages/Serilog.Sinks.AzureDocumentDb/3.6.8-dev-00142 and let me know if it fixes issue.

**Comment by kumprek** [comment]
Perfect, this specific Nuget Package works exactly the way expected.
