### ISSUE TITLE
Question: Is there retry logic if Azure Doc db is unreachable for any reason

### ISSUE THREAD

**Issue by aagarwal10** [serilog/serilog-sinks-azuredocumentdb#62]
Just curious if this is supported or can be supported in future.

Thanks,

**Comment by saleem-mirza** [comment]
@aagarwal10 at this time, this sink doesn't support retry logic. I intentionally dropped this feature for sake of simplicity, portability and also arguably performance. Retry needs a lot of moving parts which makes sink less portable e.g. how many times it needs to try and how often. Does it need to save log messages somewhere if sink is not able to reach destination.
If your application can't afford loosing log, I'd suggest to consider either FileSink or SQLite Sink.

**Comment by aagarwal10** [comment]
Thanks a lot for responding to the question...
