### ISSUE TITLE
.csdef file gives error when i specify <Setting name="serilog:write-to:AzureDocumentDB.endpointUrl" />

### ISSUE THREAD

**Issue by ArshathS** [serilog/serilog-sinks-azuredocumentdb#71]
When I publish my API project to Azure here is the error what i'm getting.
![image](https://user-images.githubusercontent.com/35331259/35370906-cbac4b18-01b6-11e8-80e0-ec0c59e987df.png)

Is there any way to resolve this issue and here is the code and the problem comes when this symbol "**:**" is init.
![image](https://user-images.githubusercontent.com/35331259/35370991-54bd20da-01b7-11e8-902b-6aa63008ea18.png)

**Comment by saleem-mirza** [comment]
I'm not sure what are you trying to do and where are you publishing solution? Please see

Please answer these questions before submitting your issue. Thanks!


### What is type of your application?


### What is your framework version? is it 4.5, 4.6, 4.7 or .net core 2?


### Does this issue reproduce with the latest release?


### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.


### What did you expect to see?


### What did you see instead?

**Comment by ArshathS** [comment]
Here are answers for your questions.

1. It's a web API Project
2.  4.6
3. Yes
4. Locally it's running without any issues but when it comes to release automation I should be able to change the value of endpointurl , key, and TTL manually so that I need to modify  .csfg and .csdef file environment to environment. When i do that .csdef does not support that colon mark ":" so the build fails.
![image](https://user-images.githubusercontent.com/35331259/35424542-68e71886-027a-11e8-9a42-6b35ab8dd629.png)

5. Expecting : Build is success and so that the log works as expected.
6. Actual : Build fails and log is not working as expected.

**Comment by ArshathS** [comment]
It seems this is not supported.
[https://github.com/Azure/azure-sdk-for-net/issues/792](url)

**Comment by ArshathS** [comment]
Take a look at the answer I have provided in stackoverflow.

[https://stackoverflow.com/a/48455629/5127285](url)
