### ISSUE TITLE
Serilog 3.7.0 onwards doesn't support .NETStandard anymore

### ISSUE THREAD

**Issue by carlos-sarmiento** [serilog/serilog-sinks-azuredocumentdb#74]
My team has a .NET Core Library that targets .NETStandard 1.6. We were running version 3.6.1 and decided to upgrade to 3.8.1 and saw that the requirements for the nuget package had changed to .NETCoreApp 1.0. 
Now, nuget is trying to install the .NET Framework version, which fails to compile because the underlying DocumentDB library is not .NETStandard compatible.

Is there a reason for this change?

**Comment by saleem-mirza** [comment]
@carlos-sarmiento apologies for inconvenience. I believe I was struggling with some compatibility issues so decided to drop support .NETStandard and wait for better support at that time. There are a lot of moving parts and sometime if one library breaks, it cause trickle down effect. 

However, enough justifications. I did fixed this issue in my dev branch few weeks ago, but couldn't find time to make it public.
I promise, this will get into nuget sometime this weekend. I'll keep you posted.

**Comment by amitjaura** [comment]
@saleem-mirza, thanks for working on this issue. Any update on when can this solution be public?

**Comment by saleem-mirza** [comment]
@amitjaura I have released a newer version with support to .NETStandard and few other improvements. See https://www.nuget.org/packages/Serilog.Sinks.AzureDocumentDb/4.0.0
